### ISSUE TITLE
BioModel Discussion Issue for eos3804

### ISSUE THREAD

**Issue by Zainab-ik** [ersilia-os/eos3804#5]
**Summary !!!**

- **BioModel Name**: Liu2023 -  _Acinetobacter baumannii_ growth inhibition prediction with Deep Learning .

- **BioModel Tag**: fair AIML, Machine learning model

- **Metadata Comments**: 
1.  In the publication, they made mention of an e-coli K12 as a model organism. Does that mean the host of _A. Baumannii_? If yes, that'd be an in-vitro model host and can't classify as a taxonomy in the metadata, right?

- **Contributor**:
> 
 | roles             | Names | 
 | :---------------- | :------: | 
 | Curator        |   @Zainab-ik   | 
 | Modeller       |   @miquelduranfrigola       | 
 | Reviewer       |   @GemmaTuron    | 

- **Curation status** :  manually curated

- **Annotation file**: [here](https://docs.google.com/spreadsheets/d/1SfFgFAV1oPri_fhbeIxTK30yx0khJo26oBMozDnoqoE/edit?usp=sharing)

**Comment by Zainab-ik** [comment]
@GemmaTuron Kindly review

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik 

This paper is the continuation of Chemprop (Stokes et al, 2020) which was developed in E.coli data. The model is focused only on A.baumannii.  I would look at the metadata of eos4e40 - most of it should be the same, only the organism is different.

This arises a question - are we collecting the data about whether the model is validated experimentally or not? I think that might be a valuable field to collect

**Comment by Zainab-ik** [comment]
> Hi @Zainab-ik
> 
> This paper is the continuation of Chemprop (Stokes et al, 2020) which was developed in E.coli data. The model is focused only on A.baumannii. I would look at the metadata of eos4e40 - most of it should be the same, only the organism is different.
> 
Yes, they are mostly the same.

> This arises a question - are we collecting the data about whether the model is validated experimentally or not? I think that might be a valuable field to collect

After discussing with Sheriff, the metadata _Experimental Validation_ with this [ontology](http://purl.obolibrary.org/obo/OBCS_0000143) or [this](http://purl.obolibrary.org/obo/NCIT_C43622) and the _hasProperty_ tag has been added to the annotation and it's ready for review.

**Comment by GemmaTuron** [comment]
@Zainab-ik 
For this model and others, let's clarify

The fact that the authors use a library for validating the results in this case, Drug Repurposing Hub, this is not a Data Source, and it should not be listed as such. Let's revise if this has happened in other models as well
Also, how do we highlight that a model has external validation in the lab?
And why QSAR is not in this model but it appears in others? we should be consistent with it

**Comment by Zainab-ik** [comment]
> @Zainab-ik For this model and others, let's clarify
> 
> The fact that the authors use a library for validating the results in this case, Drug Repurposing Hub, this is not a Data Source, and it should not be listed as such. Let's revise if this has happened in other models as well Also, how do we highlight that a model has external validation in the lab? And why QSAR is not in this model but it appears in others? we should be consistent with it


To clarify, validation dataset doesn't qualify as a metadata for the model. Well note.
Regarding the external validation; they are usually experimental, right? And the idea/solution is to add a **Experimental validation/Method** metadata to the annotation.
Well sorted with the QSAR.

**Comment by GemmaTuron** [comment]
The compound identification field we discussed is not relevant
The experimental validation could indicate whether it is in vitro or in vivo

**Comment by Zainab-ik** [comment]
> The compound identification field we discussed is not relevant The experimental validation could indicate whether it is in vitro or in vivo

the experimental validation is both so I added both in vivo and in vitro.

**Comment by GemmaTuron** [comment]
if all the changes are made let's add the model to biomodels!
